# Generated by Django 4.1 on 2022-08-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleSheet', '0004_alter_datas_price_in_rubles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
