version: "3.9"

services:
  db:
    image: postgres:13-alpine
    container_name: database
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql
    restart: always
    ports:
      - '5434:5432'

  web:
    container_name: web
    build: .
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    depends_on:
      - db

volumes:
  pg_data:
  static_volume:
  media_volume: